version: '2.1'
services:
  db:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 'Ilovepython'
      MYSQL_DATABASE: 'pychat'
      MYSQL_USER: 'pychat'
      MYSQL_PASSWORD: 'pypass'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfileserver
    command:
       bash -c "python manage.py init_db && python manage.py runsslserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:8000/"]
      timeout: 5s
      retries: 10
    ports:
     - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
      - redis
    volumes:
      - ./log:/usr/src/log
    environment:
      MYSQL_DATABASE: 'pychat'
      MYSQL_USER: 'pychat'
      MYSQL_PASSWORD: 'pypass'
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
      REDIS_PORT: '6379'
      REDIS_HOST: 'redis'

  redis:
    image: redis:alpine

  ws:
    build:
      context: ../
      dockerfile: ./docker/Dockerfilewebsocket
    depends_on:
      server:
        condition: service_healthy
    command: python manage.py start_tornado
    links:
      - server
    ports:
     - 8888:8888
    environment:
      MYSQL_DATABASE: 'pychat'
      MYSQL_USER: 'pychat'
      MYSQL_PASSWORD: 'pypass'
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
      REDIS_PORT: '6379'
      REDIS_HOST: 'redis'