version: '3.3'
services:
  db:
    image: mysql/mysql-server
    expose:
      - "3306"
  redis:
    image: redis:latest
    expose:
      - "6379"
  server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfileserver
    volumes:
      - ./log:/usr/src/log
    command: bash -c "python manage.py init_db && python manage.py runsslserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db
      - redis
#  ws:
#    build:
#      context: ../
#      dockerfile: ./docker/Dockerfileserver
#    ports:
#    - 8888:8888
#    depends_on:
#    - db
#    - redis
#    - server