version: '3.3'
services:
  css:
    build:
      context: ..
      dockerfile: ./docker/Dockerfilecss
    volumes:
      - css-volume:/usr/src/css
  db:
    image: mysql/mysql-server
    expose:
      - "3306"
  redis:
    image: redis:latest
    expose:
      - "6379"
  server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfileserver
    volumes:
      - css-volume:/usr/src/chat/static/css
    command: bash -c "python manage.py init_db && python manage.py runsslserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db
      - redis
      - css
  ws:
    build:
      context: ../
      dockerfile: ./docker/Dockerfileserver
    ports:
    - 8888:8888
    depends_on:
    - db
    - redis
    - server
volumes:
  css-volume: