version: '2.1'
services:
  db:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 'Ilovepython'
      MYSQL_DATABASE: 'pychat'
      MYSQL_USER: 'pychat'
      MYSQL_PASSWORD: 'pypass'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      interval: 5s
      retries: 10
    volumes:
      - ./volumes/mysql:/var/lib/mysql
  server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfileserver
    command:
       bash -c "python manage.py init_db && uwsgi --ini /usr/src/chat-uwsgi.ini"
    healthcheck:
      test:  bash -c "[ -S /tmp/socket/uwsgi.sock ]"
      retries: 10
      interval: 5s
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./volumes/log:/usr/src/log
      - ./volumes/migrations:/usr/src/chat/migrations
      - ./volumes/photos:/usr/src/photos
      - socket:/tmp/socket
      - static:/usr/src/chat/static

  redis:
    image: redis:alpine
    volumes:
      - ./volumes/redis:/data
  nginx:
    build:
      context: ../
      dockerfile: ./docker/Dockerfilenginx
    volumes:
      - socket:/tmp/socket:ro
      - ./volumes/photos/:/srv/http/photos:ro
      - static:/srv/http/static:ro
    ports:
     - 8000:443
  ws:
    build:
      context: ../
      dockerfile: ./docker/Dockerfilewebsocket
    depends_on:
      server:
        condition: service_healthy
    command:
      python manage.py start_tornado
    volumes:
      - ./volumes/log:/usr/src/log
    links:
      - server
volumes:
   socket:
   static: